services:
  - type: web
    name: picohunter-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: APP_NAME
        value: PicoHunter
      - key: DATABASE_SSL
        value: "true"
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
